### ISSUE TITLE
What is being built? We need something to build. 

### ISSUE THREAD

**Issue by Ry-E** [Ry-E/Genesis#1]
So maybe we can discuss a project here? might not be horrible

Maybe something in web3? or gaming? or web3 gaming? Itd be sweet to build out some crazy skyrim type RPG infused with nfts but the scope of that is ridiculous, so maybe like minigames? like a dapp version of doodle jump or flappy bird somehow where it would actually be reasonable to finish something in a shorter time.

Or I was thinking about streaming services paid with staking rewards, so you just stake a certain amount and you get access to content until you unstake, and the rewards would go towards whoever is serving the content? idk fuck. actually kind of sounds like filecoin or bittorent now that I typed it out.

maybe just like how sushi swap basically copied unswaps open source code and added a different feature, we could find something open source and just make a better version. Like a rocketpool clone where eth is used as collateral instead of rpl.

Or we undercut the automated cypto tax software industry.

Theres got to be something actually really interesting with nfts we could try which would be really cool

Idk what do you guys think, what ideas do you have?

**Comment by bhowl** [comment]
This sounds fun. I like the idea of web3 gaming! And I agree with starting out simple and a short-timeline project. 

**As for game ideas:**
We could draw inspo from Nintendo games 

2D game? 
If 2D, what is the camera angle? Such as from the side like classic Super Marios or overhead like Link, Ness and Pokemon. 

2.5D?
This is creating 3D objects (assets) within a 2D space such as Metorid Dread and Link's Awakening

3D?
Asset creation seems difficult but if we don't have a ton of assets then maybe

Side: [Nintendo's indie games](https://www.nintendo.com/store/games/indie-games/) - I think Nintendo has a strong indie game [developer](https://developer.nintendo.com/) community, so getting a game on Nintendo isn't unfeasible. However, I'm sure there are some challenges. Throw web3 or any blockchain into the mix... probably not possible but just an idea idk 
*edit: readability

**Comment by bhowl** [comment]
Something like [Ness Earthbound](https://www.youtube.com/watch?v=xTonuqUL_MU) but with an ingame digital currency slash a Proof of Stake aspect... or even something for a Proof of Location or something.

**Comment by Ry-E** [comment]
I wonder if we could do like a smash bros remake where your character is customizable and has upgradeable skills/weapons/gear and allows selling your earned rewards using blockchain. Could be a simple-ish 2d platformer with basically just attack functionality. maybe we could add modes like a giant smash bros battle royal

**Comment by Ry-E** [comment]
I know people give away asset packs for free on reddit so maybe we can just use those until we either want to try doing the design ourselves or we are serious enough to hire designers.

i really like pixel art for 2d games too

**Comment by Ry-E** [comment]
or maybe we could do some time of overhead 2d game, procedurally generate some world, and then we just need something simple and ideally fun for the character to do

**Comment by howl0893** [comment]
I like the idea of making a web3 game too. 2D seems like the most practical route starting out. That way we could actually handle the asset creation ourselves. I would like to make a multiplayer game. I always enjoy playing those more than a single player.

I've been floating the idea around in my head of a multiplayer game where you get to gamble on the winner. It'd be sweet to wager on yourself to win a match before going in. Pretty sure there'd be some legality issues, but if all the betting is done with  digital currency we might be able to get around some of the sports betting regulations (not too sure how that works, need to research more).

I've noticed a lot more automated cypto tax software apps this year compared to last year. Think there is more competition in that space than before. Plus being game devs sounds way more fun than tax auditors haha.

**Comment by Ry-E** [comment]
This ones a rather large scope but maybe it could start small and slowly expand. basically similar concept, 2d overhead pixel art, where their is an initial "home-world" where characters can create their own base and interact with the world in certain ways. and then you can choose to fight in the local tournament (smash bros remake), and use rewards to upgrade gear and your base. then we slowly build out other minigames for the character to join. Eventually building out our own 2d pixelverse. where items are worth real money and maybe there is an elected gov for laws but everything is done with blockchain

**Comment by Ry-E** [comment]
The last one i want to throw out there is just a video game production DAO, where we just create the dao and then let the people decide on what game to build

**Comment by Ry-E** [comment]
So it seems like we are heading in this direction:

- 2d gaming
- web3
- multiplayer
- betting 

Maybe a zelda styled battle royal? just a big map, and players fighting, play to earn somehow

**Comment by howl0893** [comment]
I'm sold. I've been wanting to make a smash bros remake since starting that little turtle android app in college ([reminder](https://www.youtube.com/watch?v=FsPnn5cmEWE)). 
lol, no gravity.

Large scope but gives a good road map of where we could go with it.
I like the video game production DAO idea, but it does sound a little tricky.

**Comment by Ry-E** [comment]
Oh hell yeah, that seems like the path of least resistance in regards to our skills and desires.

NFT infused smash bros. Just to start, relatively simple. 

Brad if you are good with this I think we could go ahead and close this issue

**Comment by bhowl** [comment]
Im good with it - all great ideas!
Base camp and arenas for multiplayer gladiator-pixel fighting would be awesome

**Comment by Ry-E** [comment]
Sweet. one issue down fellas.
