### ISSUE TITLE
Game theme? 

### ISSUE THREAD

**Issue by Ry-E** [Ry-E/Genesis#5]
While i do think we should focus on the mini game aspect as much as possible, we do need to decide on a theme/genre and eventually flesh out some story.
What world is our game taking place in? Northern Guilds is vikings, skyrim is more general fantasy, sci-fi futuristic. 

its hard to think of something unique but something more specific would probably limit our scope and make it easier. Part of me does want an open-world space thing but that would most likely mean spaceships flying to different planets and that is a huge project. maybe it wouldn't be horrible if we just procedurally generated everything. I was thinking anyway it might be nice to initially just procedurally generate everything and then we slowly introduce custom items and design as we go, and then we could focus on the mini-games while there is still somewhat of a world to explore outside of them

Themes that exist just to get us thinking and maybe we can do something unique:
-Sci-Fi 
-Fantasy (dragons, elves, etc.) (a lot of themes are potential subsets of fantasy too)
-Medieval
-Post-apocalypse
-Zombies
-Pirates + Vikings (Any random warrior culture, ie Samurai)
-Pre-historic (Dinos/cavemen)

Maybe some weird combination

**Comment by howl0893** [comment]
I'm a fan of all of the above. A space game would allow us to incorporate almost all of those too. Like all the different smash bro characters could be from different planets or galaxies. & some planets could have zombies or dinosaurs, etc. So it'd be like a Sci-Fi fantasy mix.. starwars-esque
Starting out we could maybe just animate space travel while we work on the rpg/smash bros modes. & then eventually include being able to fly around in your spaceship.

**Comment by bhowl** [comment]
Eventually building it up to be an RPG with spaceships would be awesome - so I vote for that as well. 
I imagine it starts at the base of a massive gladiator arena there is the town with shops and training areas and what not. The arena is like a normal stadium so for the smash bro events there are fans all around like rocket league, however, the staging of the fighting area is different depending on user choice. 
Once the game grows there will be different arena's/arena-cities that players can fly into. 
So I'm thinking a Sci-Fi/Sports theme. Each fighter is an athlete so to speak and everyone wants to be a top fighter. SmashBros is Battle Royal esque and I want ours to be somewhat of a spin on that.

**Comment by Ry-E** [comment]
Okay sweet, so we'll start with the smallest scale we can and just continually expand
