### ISSUE TITLE
you guys are pretty lame for not coming to Washignton while we had an extra space for you

### ISSUE THREAD

**Issue by bhowl** [Ry-E/Genesis#7]

**Comment by Ry-E** [comment]
Use me as the sacrificial lamb, the fault lies with me I'm afraid. I'm waiting on the paper work for the van from my brother, he had lost the title and registration so it hasn't been legal to drive, tho i did pay for it months ago. Matt tried to get the trip going and I was hoping I could take the van but I'm still waiting... kinda screwed me out of a vail trip too. I know plane would have been a reasonable substitute but I really wanted to get the van in action. I am drenched in shame :'(

**Comment by bhowl** [comment]
![image](https://user-images.githubusercontent.com/67282700/165386728-2a08536f-4ea9-4b7b-a539-bb9742be4fd0.png)
at least there was an attempt... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... maybe next year

**Comment by howl0893** [comment]
https://user-images.githubusercontent.com/46509696/165406552-7c6cd2cf-5702-46fe-a99a-60c3598a27b4.mp4

**Comment by howl0893** [comment]
We should organize a summertime trip

**Comment by bhowl** [comment]
https://youtu.be/XdnrASDr2i4

**Comment by bhowl** [comment]
https://youtu.be/vutTXcvXxUc
